### ISSUE TITLE
Hello! Could you give me resources of CS106B Fall Quarter 2020?

### ISSUE THREAD

**Issue by Ealien** [superbrace/programming-abstractions-in-cpp#1]

**Comment by obrc** [comment]
Detail ?

**Comment by Ealien** [comment]
The original assignment starter codes. Thank you very much.

**Comment by obrc** [comment]
You can find the files in page https://web.stanford.edu/class/archive/cs/cs106b/cs106b.1204/

**Comment by Ealien** [comment]
Thank you so much!
